spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Unoffimap
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234qwer

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # 엔티티 자동 생성 방식
    properties:
      hibernate:
        format_sql: true  # SQL 포맷팅
        show_sql: true    # SQL 로그 출력
